### ISSUE TITLE
Review: JS Advanced

### ISSUE THREAD

**Issue by AlekseiIvshin** [igos1/Epam#1]
Task1 - 1 - Проверь с compare(2,'1'). На оценку 2 должна быть ошибка
Task2 - 2 - в пункте “а” - не стоит менять исходный код функции random, ожидалось что вызвав её ты создашь цепочку вызовов
Task3 - 2
Task4 - 1 - не забывай про bind. Нет карринга функции (для выполнения доп. задания)
Task5 - 1 - Дополнительная часть работает не по требованиям задачи(посмотри как работают setInterval & setTimeout, в чем их отличие)

**Итоговая оценка 1**

**Comment by igos1** [comment]
и тут вроде тоже

**Comment by AlekseiIvshin** [comment]
Task1 - 2
Task2 - 2 - в пункте “а” - не стоит менять исходный код функции random, ожидалось что вызвав её ты создашь цепочку вызовов
Task3 - 2
Task4 - 2
Task5 - 2 - используй с setTimeout clearTimeout

**Итоговая оценка 2**

**Форматируй код и не используй кириллицу, если есть проблемы с кодировка**
