### ISSUE TITLE
Review: JS Advanced. Prototype & OOP

### ISSUE THREAD

**Issue by AlekseiIvshin** [igos1/Epam#2]
Task1 - 1 - Все ок, но  proto не принято прописывать внутри объекта
Task2 - 0 - Строки 11-14 - Поля объекта следует задавать внутри объекта. Нет перегрузки метода класса Car в классе MonsterTruck с вызовом родительского класса. То же самое с методом move у Bike. Нет вызова родительского конструктора.
Task3 - 0 Аналогично Task2 + наследование предполагает, что проверка instanceof со всеми родительскими классами будет возвращать true. Например, `new MonsterTruck() instanceof Vehical -> true`
Task4 - 2

**Итоговая оценка 0**

Беда с кодировкой.

**Comment by igos1** [comment]
Вроде исправил

**Comment by AlekseiIvshin** [comment]
Task1 - 1
Task2 - 0 - Есть ошибки в реализации 
- Советы по классам: группируй код одного класса в одном месте, не "размазывай" по всему скрипту
- Проверь чему равен Bike.prototype.constructor через  console.log внизу и сравни с тем, что ты задавал
Task3 - 0 - Есть ошибки в реализации
Добавь следующий код  и запусти: 
```
var myBike = new Bike();
console.log(myBike.move());
```
Task4 - 2

**Итоговая оценка 0**

**Беда с кодировкой.**

**Comment by AlekseiIvshin** [comment]
Task1 - 1
Task2 - 1
Task3 - 1 - Проверь чему равен Bike.prototype.constructor через console.log внизу и сравни с тем, что ты задавал
Task4 - 2

**Итоговая оценка 2** (вне зачета)

# Беда с кодировкой.
